apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{cookiecutter.project_slug}}
  labels:
    app: {{cookiecutter.project_slug}}
spec:
  rules:
  - host: {{cookiecutter.domain}}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{cookiecutter.project_slug}}
            port:
              number: 80
